[package]
name = "testing_nannou"
version = "0.1.0"
authors = ["tilacog <tilacog@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.17.0"
